At least compiling now

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -34,6 +34,7 @@ USE_MPICXX=0
 USE_UPCXX=0
 USE_PTHREADS=0
 USE_OPENMP=0
+USE_PYHON=0
 DETECTED_MPI=0
 DETECTED_UPCXX=0
 MPICXX=
@@ -101,6 +102,10 @@ if [ "$UPCXX" != "" ]; then
  fi
 fi
 
+echo "[Korali] Checking for Python support..."
+python --version > /dev/null 2>&1
+if [ $? -eq 0 ]; then USE_PYTHON=1; fi
+
 if [ "$MPICXX" != "" ]; then
  echo "[Korali] Checking for MPI with $MPICXX command..."
  $MPICXX --version > /dev/null 2>&1
@@ -114,7 +119,7 @@ fi
 compiler=""
 
 if [ $DETECTED_MPI -eq 1 ]; then
-  echo "[Korali] Configuring with support for MPI Conduit/Applications using $MPICXX.";
+  echo "[Korali] Configuring with support for MPI Conduit/Applications using $MPICXX."
   compiler="CXX=$MPICXX"
   mpiFlags=-D_KORALI_USE_MPI
 else
@@ -123,7 +128,7 @@ else
 fi
 
 if [ $DETECTED_UPCXX -eq 1 ]; then
-  echo "[Korali] Configuring with support for UPC++ Conduit/Applications using $UPCXX.";
+  echo "[Korali] Configuring with support for UPC++ Conduit/Applications using $UPCXX."
   compiler="CXX=$UPCXX"
   upcxxFlags=-D_KORALI_USE_UPCXX
 else
@@ -132,19 +137,27 @@ else
 fi
 
 if [ $USE_PTHREADS -eq 1 ]; then
-  echo "[Korali] Configuring with support for the Pthreads Conduit.";
+  echo "[Korali] Configuring with support for the Pthreads Conduit."
   pthreadFlags="-pthread -D_KORALI_USE_PTHREADS"
 else
-  echo "[Korali] Configuring without support for the Pthreads Conduit.";
+  echo "[Korali] Configuring without support for the Pthreads Conduit."
   pthreadFlags=
 fi
 
 if [ $USE_OPENMP -eq 1 ]; then
-  echo "[Korali] Configuring with support for the OpenMP Conduit.";
+  echo "[Korali] Configuring with support for the OpenMP Conduit."
   openMPFlags="-fopenmp -D_KORALI_USE_OPENMP"
 else
-  echo "[Korali] Configuring without support for the OpenMP Conduit.";
+  echo "[Korali] Configuring without support for the OpenMP Conduit."
   openMPFlags=
+fi
+
+if [ $USE_PYTHON -eq 1 ]; then
+  echo "[Korali] Configuring with support for Python."
+  pythonFlags="\$(shell python3 -m pybind11 --includes) -Wno-deprecated-declarations"
+else
+  echo "[Korali] Configuring without support for Python."
+  PythonFlags=
 fi
 
 if [ $USE_UPCXX  -eq 1 ]; then compiler=$UPCXX;  fi
@@ -155,7 +168,7 @@ echo "$compiler" > common.mk
 echo "PREFIX = $PREFIX" >> common.mk
 echo "CXXFLAGS = -O3 -g" >> common.mk
 echo "#CXXFLAGS = -O0 -g" >> common.mk 
-echo "CXXFLAGS += -std=c++17 -Wall -Wfatal-errors \`gsl-config --cflags\` $pthreadFlags $openMPFlags $upcxxFlags $mpiFlags" >> common.mk
+echo "CXXFLAGS += -std=c++17 -Wall -Wfatal-errors \`gsl-config --cflags\` $pthreadFlags $openMPFlags $upcxxFlags $mpiFlags $pythonFlags" >> common.mk
 echo "LDFLAGS = \`gsl-config --libs\` -lm $openMPFlags $pthreadFlags" >> common.mk
 echo "COMPILE.cxx = \$(CXX) \$(CXXFLAGS) -c -o \$@" >> common.mk
 echo "LINK.o      = \$(CXX) \$(LDFLAGS)  -o \$@" >> common.mk
