Adding checks for pip3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -158,18 +158,7 @@ fi
 
 ######## Checking support for Python3 ########
 
-echo "[Korali] Checking for Python3 support using \"python3 -m pybind11 -h\"..."
-python3 -m pybind11 -h > /dev/null 2>&1
-if [ $? -ne 0 ]; then
-  echo "[Korali] Error: pybind11 not found."
-  echo "[Korali] Solution: Install pybind11 with \"pip3 install --user pybind11\"."
-  exit -1
-fi
-echo "[Korali] Pybind11 found."
-
-######## Checking support for Pybind11 ########
-
-echo "[Korali] Checking for Pybind11 support using \"python3 --version\"."
+echo "[Korali] Checking for Python3 support using \"python3 --version\"."
 pyver=`python3 --version`
 if [ $? -eq 0 ]; then
   echo "[Korali] Checking for python3-config."
@@ -185,6 +174,28 @@ else
   exit -1
 fi
 echo "[Korali] Python3 version $pyver found."
+
+######## Checking support for pip3 ########
+
+echo "[Korali] Checking for pip3 support using \"pip3 --version\"..."
+pip3 --version > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo "[Korali] Error: pip3 not found."
+  echo "[Korali] Solution: Make sure pip3 is correctly installed in your system"
+  exit -1
+fi
+echo "[Korali] Pip3 found."
+
+######## Checking support for Pybind11 ########
+
+echo "[Korali] Checking for Pybind11 support using \"python3 -m pybind11 -h\"..."
+python3 -m pybind11 -h > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo "[Korali] Error: pybind11 not found."
+  echo "[Korali] Solution: Install pybind11 with \"pip3 install --user pybind11\"."
+  exit -1
+fi
+echo "[Korali] Pybind11 found."
 
 ######## Checking selected compiler #######
 
