Improving config

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -38,7 +38,7 @@ case $i in
     *)
     print_help
     echo ""
-    echo "[Korali] Error: Unknown option $i."       
+    echo -e "[Korali] \e[31mError:\e[0m  Unknown option $i."       
     exit 1
     ;;
 esac
@@ -102,18 +102,19 @@ then
  cmpver=`printf "${gslver}\n${mingslver}" | sort -V | head -n 1`
  if [[ "$cmpver" != "$mingslver" ]]; then
    echo -e "[Korali] \e[31mError:\e[0m GSL Version found (${gslver}) is smaller than required (${mingslver})."
-   echo -e "[Korali] \e[32mSolution:\e[0m Run ./tools/install-reqs gsl to install a local GSL automatically."
+   echo -e "[Korali] \e[32mSolution:\e[0m Run ./tools/install-gsl to install a local GSL version automatically."
    exit -1
  fi
 fi
 
 ######## Checking support for MPI ########
 
+echo "[Korali] Checking for MPI support using \"$MPICXX --version\"..."
 $MPICXX --version > /dev/null 2>&1
 if [ ! $? -eq 0 ]
 then
- echo "[Korali] No MPI compiler command found in \$MPICXX."
- echo "[Korali] Use 'export MPICXX=(path)' to enable MPI support."
+ echo -e "[Korali] \e[33mWarning:\e[0m No MPI compiler command found in \$MPICXX."
+ echo -e "[Korali] \e[36mSuggestion:\e[0m Use 'export MPICXX=(path)' to enable MPI support."
  USE_MPI=0
 else
  echo "[Korali] Found $MPICXX for MPI compiler/wrapper."
@@ -125,20 +126,31 @@ fi
 
 ######## Checking support for Python3 ########
 
-echo "[Korali] Checking for Python3 support using \"python3 --version\"."
+echo "[Korali] Checking for Python3 support using \"python3 -m pybind11 -h\"..."
+python3 -m pybind11 -h > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+  echo -e "[Korali] \e[31mError:\e[0m pybind11 not found."
+  echo -e "[Korali] \e[32mSolution:\e[0m Install pybind11 with \"pip3 install --user pybind11\"."
+  exit -1
+fi
+echo "[Korali] Pybind11 found."
+
+######## Checking support for Pybind11 ########
+
+echo "[Korali] Checking for Pybind11 support using \"python3 --version\"."
 pyver=`python3 --version`
 if [ $? -eq 0 ]; then
   echo "[Korali] Checking for python3-config."
   python3-config --help > /dev/null 2>&1
   if [ $? -ne 0 ]; then
-    echo "[Korali] Error: python3-config not found."
-    echo "[Korali] Please make sure python3 is correctly installed."
+    echo -e "[Korali] \e[31mError:\e[0m python3-config not found."
+    echo -e "[Korali] \e[32mSolution:\e[0m Please make sure python3 is correctly installed."
     exit
   fi
 else
-  echo "[Korali] Error: Python3 not found."
-  echo "[Korali] Please make sure the python3-config command is accesible in the PATH environment variable."
-  exit
+  echo -e "[Korali] \e[31mError:\e[0m Python3 not found."
+  echo -e "[Korali] \e[32mSolution:\e[0m Please make sure the python3-config command is accesible in the PATH environment variable."
+  exit -1
 fi
 echo "[Korali] Python3 version $pyver found."
 
@@ -146,7 +158,8 @@ echo "[Korali] Python3 version $pyver found."
 
 if [[ "$USE_CXX" == "" ]]
 then
-  echo "[Korali] Error: Did not found any valid C++ or MPI C++ compiler. Please define \$CXX."
+  echo -e "[Korali] \e[31mError:\e[0m  Did not found any valid C++ or MPI C++ compiler."
+  echo -e "[Korali] \e[32mSolution:\e[0m Please define a valid C++ compiler in \$CXX."
   exit -1
 fi
 
