Improving installation logging

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+logFile=install.log
+
 # Help display function
 function print_help ()
 {
@@ -21,6 +23,26 @@ function print_help ()
  echo " --install-gsl Automatically downloads and installs GSL if not found."
  echo " --rebuild Cleans and rebuilds/installs Korali for development purposes."
  echo " --help Displays this help message."
+}
+
+# Logging and printing function.
+function logEcho ()
+{
+ echo "$1"
+ echo "$1" >> $logFile
+}
+
+# Logging function.
+function log ()
+{
+ echo "$1" >> $logFile
+}
+
+# Exit with error message.
+function exitWithError ()
+{
+ echo "[Korali] Installation Error: Check $logFile for more information." >> $logFile
+ exit -1
 }
 
 INSTALLGSL=0
@@ -50,37 +72,43 @@ case $i in
 esac
 done
 
-echo "[Korali] Configuring Korali..."
 
-######## Checking Architecture ####
+######## Start Configuration ######
 
-# Checking for architecture
+echo "Korali Log Start." > $logFile
+logEcho "[Korali] Configuring Korali..."
+
+log "Checking for architecture..."
 arch="$(uname -s)"
 
 # Linux Architecture is default
 SHAREDLIB_FLAG="-shared"
 
 if [ "$arch" == "Linux" ]; then
-echo "[Korali] Linux System Detected."
+ log "[Korali] Linux System Detected."
 fi
 
 # If using MacOs, change flags 
 if [ "$arch" == "Darwin" ]; then
- echo "[Korali] MacOS (Darwin) System Detected."
+ log "[Korali] MacOS (Darwin) System Detected."
  SHAREDLIB_FLAG="-dynamiclib"
 fi
 
 ######## Checking Compiler ########
 
-$CXX --version > /dev/null 2>&1
+logEcho "[Korali] Checking Pre-requisites..."
+
+log "Checking for C++ Compiler..."
+
+$CXX --version >> install.log 2>&1
 DETECTED_CXX=$?
-c++ --version > /dev/null 2>&1
+c++ --version >> install.log 2>&1
 DETECTED_CPLUSPLUS=$?
-g++ --version > /dev/null 2>&1
+g++ --version >> install.log 2>&1
 DETECTED_GXX=$?
-clang++ --version > /dev/null 2>&1
+clang++ --version >> install.log 2>&1
 DETECTED_CLANG=$?
-icpc --version > /dev/null 2>&1
+icpc --version >> install.log 2>&1
 DETECTED_ICPC=$?
  
 USE_CXX=""
@@ -92,7 +120,7 @@ if [ $DETECTED_CXX       -eq 0 ]; then USE_CXX=$CXX;    fi;
 
 ######## Checking support for GNU Scientific Library ########
 
-echo "[Korali] Looking for existing GNU Scientific Library (GSL)."
+log "[Korali] Looking for existing GNU Scientific Library (GSL)..."
 
 gslprefix=$PWD/build
 
@@ -101,39 +129,39 @@ if [ ! -f "$gslcfgFile" ]; then
  gslcfgFile=gsl-config
 fi
 
-echo "[Korali] Running \"$gslcfgFile --version\"..."
+log "[Korali] Running \"$gslcfgFile --version\"..."
 gslver=`$gslcfgFile --version`
 mingslver=2.5
 if [  $? -eq 0 ]
 then
- echo "[Korali] Found GSL version $gslver."
+ log "[Korali] Found GSL version $gslver."
  cmpver=`printf "${gslver}\n${mingslver}" | sort -V | head -n 1`
  if [[ "$cmpver" != "$mingslver" ]]; then
   if [ $INSTALLGSL -eq 0 ]; then
-   echo "[Korali] Error: GSL Version found (${gslver}) is smaller than required (${mingslver})."
-   echo "[Korali] Solution: Run \"./install --install-gsl\"."
-   exit -1
+   logEcho "[Korali] Error: GSL Version found (${gslver}) is smaller than required (${mingslver})."
+   logEcho "[Korali] Solution: Run \"./install --install-gsl\"."
+   exitWithError
   else
-   echo "[Korali] Downloading GNU Scientific Library... "
+   logEcho "[Korali] Downloading GNU Scientific Library... "
    mkdir -p $PREFIX
    CURDIR=$PWD
    rm -f gsl-2.5.tar.gz 
    wget "ftp://ftp.gnu.org/gnu/gsl/gsl-2.5.tar.gz" 
-   tar -xzvf gsl-2.5.tar.gz > /dev/null 2>&1
+   tar -xzvf gsl-2.5.tar.gz >> install.log 2>&1
    echo "[Korali] Configuring GNU Scientific Library... "
    cd gsl-2.5 
-   ./configure --prefix=$gslprefix > /dev/null 2>&1 
-   echo "[Korali] Compiling GNU Scientific Library... "
-   make -j10 > /dev/null 2>&1
-   echo "[Korali] Installing GNU Scientific Library... "
-   make install > /dev/null 2>&1
+   ./configure --prefix=$gslprefix >> install.log 2>&1 
+   logEcho "[Korali] Compiling GNU Scientific Library... "
+   make -j10 >> install.log 2>&1
+   logEcho "[Korali] Installing GNU Scientific Library... "
+   make install >> install.log 2>&1
    if [  $? -ne 0 ]; then
-    echo -e "[Korali] \e[31mError: Failed GNU Scientific Library installation."
-    exit -1
+    logEcho -e "[Korali] \e[31mError: Failed GNU Scientific Library installation."
+    exitWithError
    fi
    cd .. 
-   rm -rf gsl-2.5 gsl-2.5.tar.gz > /dev/null 2>&1
-   echo "[Korali] Finished installing GNU Scientific Library. "
+   rm -rf gsl-2.5 gsl-2.5.tar.gz >> install.log 2>&1
+   logEcho "[Korali] Finished installing GNU Scientific Library. "
    gslcfgFile=$gslprefix/bin/gsl-config
   fi
  fi
@@ -142,68 +170,67 @@ fi
 ######## Checking support for MPI ########
 
 MPIFLAGS=""
-echo "[Korali] Checking for MPI support..."
-echo "[Korali] Running \"\$MPICXX --version\"..."
-$MPICXX --version > /dev/null 2>&1
+log "[Korali] Checking for MPI support..."
+log "[Korali] Running \"\$MPICXX --version\"..."
+$MPICXX --version >> install.log 2>&1
 if [ ! $? -eq 0 ]
 then
- echo "[Korali] Warning: No MPI compiler command found in \$MPICXX."
- echo "[Korali] Suggestion: Use 'export MPICXX=(path)' to enable MPI support."
+ logEcho "[Korali] Info: No MPI compiler command found in \$MPICXX."
+ logEcho "[Korali] Suggestion: Use 'export MPICXX=(path)' to enable MPI support."
  USE_MPI=0
 else
- echo "[Korali] Found $MPICXX for MPI compiler/wrapper."
- echo "[Korali] Use 'export MPICXX=(path)' to use a different MPI wrapper."
- echo "[Korali] Configuring with support for the MPI Conduit"
+ log "[Korali] Found $MPICXX for MPI compiler/wrapper."
+ log "[Korali] Use 'export MPICXX=(path)' to use a different MPI wrapper."
  USE_CXX=$MPICXX
  MPIFLAGS="-D_KORALI_USE_MPI"
 fi
 
 ######## Checking support for Python3 ########
 
-echo "[Korali] Checking for Python3 support using \"python3 --version\"."
+log "[Korali] Checking for Python3 support using \"python3 --version\"."
 pyver=`python3 --version`
 if [ $? -eq 0 ]; then
-  echo "[Korali] Checking for python3-config."
-  python3-config --help > /dev/null 2>&1
+  log "[Korali] Checking for python3-config."
+  python3-config --help >> install.log 2>&1
   if [ $? -ne 0 ]; then
-    echo "[Korali] Error: python3-config not found."
-    echo "[Korali] Solution: Please make sure python3 is correctly installed."
-    exit
+    logEcho "[Korali] Error: python3-config not found."
+    logEcho "[Korali] Solution: Please make sure python3 is correctly installed."
+    exitWithError
   fi
 else
-  echo "[Korali] Error: Python3 not found."
-  echo "[Korali] Solution: Please make sure the python3-config command is accesible in the PATH environment variable."
-  exit -1
+  logEcho "[Korali] Error: Python3 not found."
+  logEcho "[Korali] Solution: Please make sure the python3-config command is accesible in the PATH environment variable."
+  exitWithError
 fi
-echo "[Korali] Python3 version $pyver found."
+log "[Korali] Python3 version $pyver found."
 
 ######## Checking support for pip3 ########
 
-echo "[Korali] Checking for pip3 support using \"pip3 --version\"..."
-pip3 --version > /dev/null 2>&1
+log "[Korali] Checking for pip3 support using \"pip3 --version\"..."
+pip3 --version >> install.log 2>&1
 if [ $? -ne 0 ]; then
-  echo "[Korali] Error: pip3 not found."
-  echo "[Korali] Solution: Make sure pip3 is correctly installed in your system"
-  exit -1
+  logEcho "[Korali] Error: pip3 not found."
+  logEcho "[Korali] Solution: Make sure pip3 is correctly installed in your system"
+  exitWithError
 fi
 
 ######## Checking support for Pybind11 ########
 
-echo "[Korali] Checking for Pybind11 support using \"python3 -m pybind11 -h\"..."
-python3 -m pybind11 -h > /dev/null 2>&1
+log "[Korali] Checking for Pybind11 support using \"python3 -m pybind11 -h\"..."
+python3 -m pybind11 -h >> install.log 2>&1
 if [ $? -ne 0 ]; then
-  echo "[Korali] Error: pybind11 not found."
-  echo "[Korali] Solution: Install pybind11 with \"pip3 install --user pybind11\"."
-  exit -1
+  logEcho "[Korali] Error: pybind11 not found."
+  logEcho "[Korali] Solution: Install pybind11 with \"pip3 install --user pybind11\"."
+  exitWithError
 fi
 
 ######## Checking selected compiler #######
 
 if [[ "$" == "" ]]
 then
-  echo "[Korali] Error:  Did not found any valid C++ or MPI C++ compiler."
-  echo "[Korali] Solution: Please define a valid C++ compiler in \$CXX."
-  exit -1
+  logEcho "[Korali] Error:  Did not found any valid C++ or MPI C++ compiler."
+  logEcho "[Korali] Solution: Please define a valid C++ compiler in \$CXX or \$MPICXX."
+  exitWithError
 fi
 
 ######## Determining Library Flags ########
@@ -218,6 +245,8 @@ PYBIND11LIBS=`python3-config --ldflags`
 
 ######## Creating Compilation Config File ########
 
+log "[Korali] Creating Compilation Config File..."
+
 echo "CXX=$USE_CXX" > source/Makefile.conf
 echo "SHAREDLIB_FLAG=$SHAREDLIB_FLAG" >> source/Makefile.conf
 echo "MPIFLAGS=$MPIFLAGS" >> source/Makefile.conf
@@ -229,6 +258,8 @@ echo "PYBIND11INCLUDES=$PYBIND11INCLUDES" >> source/Makefile.conf
 echo "PYBIND11LIBS=$PYBIND11LIBS" >> source/Makefile.conf
 
 ######## Creating Python Config File ########
+
+log "[Korali] Creating Python Config File..."
 
 echo "#!/usr/bin/env python3" > python/cxx/cxx.conf
 echo "CXX='$USE_CXX'" >> python/cxx/cxx.conf
@@ -244,15 +275,24 @@ cat ./python/cxx/cxx.conf ./python/cxx/compiler.py.base > ./python/cxx/compiler.
 cat ./python/cxx/cxx.conf ./python/cxx/libs.py.base > ./python/cxx/libs.py
 
 ######## Compiling Korali C++ Engine #########
-echo "[Korali] Compiling Korali..."
-make -j12 -C source > /dev/null 2>&1
+
+logEcho "[Korali] Compiling Korali..."
+make -j12 -C source >> install.log 2>&1
 
 ######## Installing Korali using pip3 ########
-echo "[Korali] Installing Korali..."
+logEcho "[Korali] Installing Korali..."
 ln -sf ./python/setup/setup.py setup.py
-pip3 install . --user --upgrade > /dev/null 2>&1
+pip3 install . --user --upgrade >> install.log 2>&1
+
+if [ $? -ne 0 ]; then
+  logEcho "[Korali] Error installing Korali's Python module."
+  logEcho "[Korali] Check $logFile for further information."
+  exitWithError
+fi
+
 rm -f setup.py
-echo '------------------------------------------------------------------'
-echo '[Korali] Finished installation successfully.'
-echo '------------------------------------------------------------------'
+
+echo "------------------------------------------------------------------"
+echo "[Korali] Finished installation successfully (see $logFile)."
+echo "------------------------------------------------------------------"
 
