Added install script for libGP

diff --git a/install b/install
--- a/install
+++ b/install
@@ -165,6 +165,17 @@ else
  git submodule update --remote >> $logFile 2>&1; check 
 fi
 
+
+## Looking for CMake
+
+./external/install_CMake.sh $installFlag --jobs=$NJOBS
+if [ ! $? == 0 ]; then
+ logEcho "[Korali] Error: CMake not found or older version than 3.0. Solutions:"
+ logEcho "         . Have 'cmake' version >3.0 correctly installed and in your PATH environment variable"
+ logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
+ exitWithError
+fi
+
 ## Looking for Eigen
 
 if [ ! -f ./external/eigen/Eigen/Core ]; then
@@ -174,6 +185,7 @@ if [ ! -f ./external/eigen/Eigen/Core ]; then
 fi
 
 ## Making libco
+
 logEcho "[Korali] Building libco..."
 pushd external/libco/ >> $logFile 2>&1; check
  CXX=$USE_CXX make >> $logFile 2>&1; check
@@ -185,21 +197,19 @@ if [ ! -f external/libco/libco.o ]; then
  exitWithError
 fi
 
-## Looking for CMake
-
-#./external/install_CMake.sh $installFlag --jobs=$NJOBS
-#if [ ! $? == 0 ]; then
-# logEcho "[Korali] Error: CMake not found or older version than 3.0. Solutions:"
-# logEcho "         . Have 'cmake' version >3.0 correctly installed and in your PATH environment variable"
-# logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
-# exitWithError
-#fi
-
 ## Looking for GSL
 ./external/install_gsl.sh $installFlag --jobs=$NJOBS
 if [ ! $? == 0 ]; then
  logEcho "[Korali] Error: GSL not found or older version than 2.5. Solutions"
  logEcho "         . Have 'gsl-config' version >2.5 correctly installed and in your PATH environment variable"
+ logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
+ exitWithError
+fi
+
+## Looking for libGP
+./external/install_libGP.sh $installFlag --jobs=$NJOBS
+if [ ! $? == 0 ]; then
+ logEcho "[Korali] libGP not found. Try either of these solutions:"
  logEcho "         . Run './install --prereqs' to allow Korali install missing prerequisites automatically."
  exitWithError
 fi
@@ -285,11 +295,16 @@ echo "[Korali] Creating configuration files..."
 
 DNNLROOT=`readlink external/oneDNNlink`; check
 ONEDNNCFLAGS="-D_KORALI_USE_ONEDNN -I${DNNLROOT}/include"
-ONEDNNLDFLAGS="-Wl,-rpath -Wl,${DNNLROOT}/lib64/ -L${DNNLROOT}/lib64/ -Wl,-rpath -Wl,${DNNLROOT}/lib/ -L${DNNLROOT}/lib/ -ldnnl"
+ONEDNNLIBS="-Wl,-rpath -Wl,${DNNLROOT}/lib64/ -L${DNNLROOT}/lib64/ -Wl,-rpath -Wl,${DNNLROOT}/lib/ -L${DNNLROOT}/lib/ -ldnnl"
+
+LIBGPROOT=`readlink external/libGPlink`; check
+LIBGPCFLAGS="-I${LIBGPROOT}/include"
+LIBGPLIBS="-Wl,-rpath -Wl,${LIBGPROOT}/lib64/ -L${LIBGPROOT}/lib64/ -Wl,-rpath -Wl,${LIBGPROOT}/lib/ -L${LIBGPROOT}/lib/ -lgp"
  
 GSLPREFIX=`./external/gsl-config --prefix`; check
 GSLCFLAGS=`./external/gsl-config --cflags`; check
 GSLLIBS=`./external/gsl-config --libs`; check
+GSLLIBS="${GSLLIBS} -L${GSLPREFIX}/lib -Wl,-rpath -Wl,${GSLPREFIX}/lib"
 
 PYBIND11INCLUDES=`python3 -m pybind11 --includes` ; check
 PYBIND11LIBS=`python3-config --ldflags`; check
@@ -324,7 +339,9 @@ echo CXXARCH=$CXXARCH >> source/Makefile.conf
 echo SHAREDLIB_FLAG=$SHAREDLIB_FLAG >> source/Makefile.conf
 echo MPIFLAGS=$MPIFLAGS >> source/Makefile.conf
 echo ONEDNNCFLAGS=$ONEDNNCFLAGS >> source/Makefile.conf
-echo ONEDNNLDFLAGS=$ONEDNNLDFLAGS >> source/Makefile.conf
+echo ONEDNNLIBS=$ONEDNNLIBS >> source/Makefile.conf
+echo LIBGPCFLAGS=$LIBGPCFLAGS >> source/Makefile.conf
+echo LIBGPLIBS=$LIBGPLIBS >> source/Makefile.conf
 echo OPTFLAGS=$OPTFLAGS >> source/Makefile.conf
 echo MACHINEARCH=$arch >> source/Makefile.conf
 
