Advancing with nonintrusive

diff --git a/install b/install
--- a/install
+++ b/install
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-logFile=install.log
+logFile=$PWD/install.log
 
 # Help display function
 function print_help ()
@@ -286,7 +286,12 @@ cat ./python/cxx/cxx.conf ./python/cxx/libs.py.base > ./python/cxx/libs.py
 ######## Compiling Korali C++ Engine #########
 
 logEcho "[Korali] Compiling Korali..."
-make -j12 -C source >> install.log 2>&1
+make -j24 -C source >> install.log 2>&1
+if [ $? -ne 0 ]; then
+  logEcho "[Korali] Error compiling Korali."
+  logEcho "[Korali] Check $logFile for further information."
+  exitWithError
+fi
 
 ######## Installing Korali using pip3 ########
 logEcho "[Korali] Installing Korali..."
